### ISSUE TITLE
Unable to run the app locally

### ISSUE THREAD

**Issue by Githubbubber** [Githubbubber/BuzzBites_app#2]
**In the command line**
When I run the rails app I get this message:
> Could not find proper version of railties (4.2.8) in any of the sources
> Run `bundle install` to install missing gems.

When I run bundle install I get this message:
> An error occurred while installing nokogiri (1.8.1), and Bundler
> cannot continue.
> Make sure that `gem install nokogiri -v '1.8.1'` succeeds before bundling.

When I run gem install nokogiri -v '1.8.1' I get this message:
> In Gemfile:
>   rails was resolved to 4.2.8, which depends on
>     actionmailer was resolved to 4.2.8, which depends on
>       actionpack was resolved to 4.2.8, which depends on
>         actionview was resolved to 4.2.8, which depends on
>           rails-dom-testing was resolved to 1.0.9, which depends on
>             nokogiri
> Ms-MacBook-Pro:BuzzBites_app bootybuttcheeks$ gem install nokogiri -v '1.8.1'
> Building native extensions.  This could take a while...
> Successfully installed nokogiri-1.8.1
> Parsing documentation for nokogiri-1.8.1
> Done installing documentation for nokogiri after 3 seconds
> 1 gem installed
Here is a screenshot
![screen shot 2018-02-18 at 1 51 46 pm](https://user-images.githubusercontent.com/959281/36355551-e7ddc6e0-14b2-11e8-8adf-f7d10c567aae.png)

At this point I rerun bundle install and get the same set of errors that I outlined above.

I did a sudo run for each of these commands and that got me nowhere too
![screen shot 2018-02-18 at 2 16 11 pm](https://user-images.githubusercontent.com/959281/36355791-a1284d52-14b6-11e8-9c45-7fc485478266.png)
![screen shot 2018-02-18 at 2 16 35 pm](https://user-images.githubusercontent.com/959281/36355792-a148a4bc-14b6-11e8-9e3c-96f7e5c34aac.png)
![screen shot 2018-02-18 at 2 16 58 pm](https://user-images.githubusercontent.com/959281/36355793-a1afdf1a-14b6-11e8-875a-daefb8c1e48d.png)
![screen shot 2018-02-18 at 2 17 19 pm](https://user-images.githubusercontent.com/959281/36355794-a20eae82-14b6-11e8-9421-2a529fe8944b.png)

**Comment by trystant** [comment]
So it looks like the problem at hand is installing `nokogiri` correctly, is that right?

Also, I think the latest version of 4.2 Rails is 4.2.10.  I'd update to that version, do a `bundle install`, then do a `bundle clean -f` to remove unneeded gems.  It might help with the Nokogiri install.

This is the [doc](http://www.nokogiri.org/tutorials/installing_nokogiri.html) for nokogiri issues.
 
I'll look deeper into the screenshots, but it's likely using Homebrew to install some libraries will solve/resolve that problem.

**Comment by Githubbubber** [comment]
Yes, the problem is DEFINITELY Nokogiri. It's the same problem I'm having with all three Rails apps I'm working on right now.

I did update the Rails version and it's now 4.2.10. Unfortunately the bundle install returns the same error as before: 
> An error occurred while installing nokogiri (1.8.1), and Bundler
> cannot continue.
> Make sure that gem install nokogiri -v '1.8.1' succeeds before bundling.

On top of that when I check the Rails version of my app I see the following message:
> Could not find proper version of railties (4.2.8) in any of the sources
> Run `bundle install` to install missing gems.

I will now read the resource you linked to.

**Comment by trystant** [comment]
It looks like the -f flag was changed in `bundle clean`. Check [here](https://bundler.io/v1.1/bundle_clean.html).  Try using `--force` instead.

**Comment by Githubbubber** [comment]
Oh ok. I will try it. Thanks!
